consumes:
- application/json
definitions:
  ginx.Result:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  web.SignUpReq:
    properties:
      avatar:
        type: string
      gender:
        type: string
      mobile:
        type: string
      nick_name:
        type: string
      openid:
        type: string
    type: object
  web.loginReq:
    properties:
      code:
        type: string
    type: object
info:
  contact: {}
  title: 你好同城后端API
paths:
  /users/login:
    post:
      consumes:
      - application/json
      description: 登录成功返回的token放在响应的header的x-jwt-token里面，登录之后的后续访问需要带上token，放在请求的header里面的Authorization。
      parameters:
      - description: 微信登录的临时登录凭证
        in: body
        name: code
        required: true
        schema:
          $ref: '#/definitions/web.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":xxx,"data":{},"msg":"xxx"}'
          schema:
            $ref: '#/definitions/ginx.Result'
      summary: 用户登录接口
      tags:
      - 用户相关接口
  /users/signup:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 注册参数
        in: body
        name: signup
        required: true
        schema:
          $ref: '#/definitions/web.SignUpReq'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":xxx,"data":{},"msg":"xxx"}'
          schema:
            $ref: '#/definitions/ginx.Result'
      summary: 用户注册接口
      tags:
      - 用户相关接口
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
