consumes:
- application/json
definitions:
  ginx.Result:
    properties:
      data: {}
      msg:
        type: string
    type: object
  web.loginReq:
    properties:
      code:
        type: string
    type: object
info:
  contact: {}
  title: 你好同城后端API
paths:
  /users/login:
    post:
      consumes:
      - application/json
      description: 登录成功返回的token放在响应的header的x-jwt-token里面，登录之后的后续访问需要带上token，放在请求的header里面的Authorization。
      parameters:
      - description: 微信登录的临时登录凭证
        in: body
        name: code
        required: true
        schema:
          $ref: '#/definitions/web.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/ginx.Result'
        "401001":
          description: 请求数据有误
          schema:
            $ref: '#/definitions/ginx.Result'
        "501001":
          description: 登录失败
          schema:
            $ref: '#/definitions/ginx.Result'
      summary: 用户登录注册接口
      tags:
      - 用户相关接口
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
